FROM docker.io/library/archlinux@sha256:f89922ba60f7f19fc82ed1b23f6d701a9c8fccf38e077623f7f5009d23870fe5

ENV NAME=archlinux-toolbox VERSION=base
LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Arch Linux toolbox containers" \
      maintainer="Anthony Rabbito <hello@anthonyrabbito.com>"

COPY extra-packages /
RUN pacman -Syu --needed --noconfirm - < extra-packages
RUN rm /extra-packages

RUN mkdir /etc/sudoers.d/ && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
RUN touch /etc/machine-id

RUN pacman -Scc --noconfirm

CMD /bin/sh

LABEL org.opencontainers.image.source https://gitlab.com/kutara/tooling
